#! /bin/sh

source ~/.profile

if [ "$(hostname)" = 'gaming-pc' ]; then
    bspc monitor DP-2 -d 1 2 3 4 5 6
    bspc monitor DP-0 -d 7 8
    bspc monitor HDMI-0 -d 9 10
    polybar primary -r &
    polybar left -r &
    polybar right -r &
elif [ "$(hostname)" = 'xps-13-9370' ]; then
    if [ "$(bspc query -M --names  | grep '^DP-2$')" ]; then
        bspc monitor eDP-1 -d 1 2 3 4 5 6
        bspc monitor DP-2 -d 7 8 9 0
        polybar primary -r &
        polybar secondary -r &
    else
        bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
        polybar primary -r &
    fi
fi

bspc config border_width            2
bspc config window_gap              12
bspc config top_padding             24

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false

bspc config normal_border_color     "#282a2e"
bspc config active_border_color     "#373b41"
bspc config focused_border_color    "#81a2be"
bspc config presel_feedback_color   "#8abeb7"

bspc rule -a firefox desktop=1 follow=off focus=off
bspc rule -a Steam desktop=5 follow=off focus=off manage=on
bspc rule -a Google-chrome desktop=6 follow=off focus=off
bspc rule -a discord desktop=7 follow=off focus=off
bspc rule -a Signal desktop=7 follow=off focus=off
bspc rule -a obsidian desktop=10 follow=off focus=off
bspc rule -a tidal-hifi desktop=10 follow=off focus=off

# X preferences
xset -b
xset -dpms
xset s 0 0
xsetroot -cursor_name left_ptr
xset fp rehash

# fix java apps being blank
wmname LG3D

# ssh/gpg keys
eval "$(ssh-agent -s)"
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

feh --recursive --bg-scale --randomize ~/Pictures/wallpapers
pgrep -x sxhkd > /dev/null || sxhkd &
# notifications
dunst &
unclutter -root &

dex -a &
