music_directory        "/mnt/share/Music"
playlist_directory     "~/.mpd/playlists"
db_file            "~/.mpd/mpd.db"
log_file        "~/.mpd/mpd.log"
pid_file        "~/.mpd/mpd.pid"
state_file        "~/.mpd/mpd.state"

audio_output {
        type            "alsa"
        name            "ALSA"
#       device          "hw:0,0"        # optional
#       format          "44100:16:2"    # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "default"       # optional
#       mixer_control   "PCM"           # optional
#       mixer_index     "0"             # optional
}


audio_output {
        type                    "fifo"
        name                    "FIFO"
        path                    "/tmp/mpd.fifo"
}
